"use client";
import { useState } from 'react';
import { generateText } from '@/lib/ai';

export default function Home() {
  const [world, setWorld] = useState({
    characters: [
      { 
        name: 'Elara, the Sun-Priestess', 
        description: 'Elara is the high priestess of the Sun Temple...',
        extra: 'Her staff is said to contain a fragment of a fallen star.'
      },
      { 
        name: 'Grak, the Stone-Hearted',
        description: 'Grak is a legendary warrior from the northern mountains...',
        extra: 'He carries a massive axe forged from the heart of a volcano.'
      }
    ],
    locations: [
      { 
        name: 'The Sunken City of Aeridor',
        description: 'An ancient city lost to the depths of the ocean...',
        extra: 'Only accessible during a solar eclipse.'
      },
      { 
        name: 'Crystal Spire Mountains',
        description: 'A treacherous mountain range with peaks made of giant, glowing crystals...',
        extra: 'The mountains are home to majestic crystal golems.'
      }
    ]
  });

  const [selectedItem, setSelectedItem] = useState(world.characters[0]);
  const [isLoading, setIsLoading] = useState(false); // <-- New state for loading

  // --- UPDATED function with loading state ---
  const handleGenerateCharacter = async () => {
    setIsLoading(true); // Set loading to true at the start
    console.log("Generating character...");
    const prompt = `Generate a new fantasy character for my world. 
    Provide a unique, cool-sounding name and a one-sentence description.
    Format the response as: "Name: [Character Name] | Description: [Character Description]"`;

    try {
      const aiResponse = await generateText(prompt);
      console.log("Raw AI Response:", aiResponse);

      const name = aiResponse.split('|')[0].replace('Name: ', '').trim();
      const description = aiResponse.split('|')[1].replace('Description: ', '').trim();

      const newCharacter = {
        name: name,
        description: description,
        extra: "This character was generated by AI."
      };

      setWorld(currentWorld => ({
        ...currentWorld,
        characters: [...currentWorld.characters, newCharacter]
      }));
      setSelectedItem(newCharacter);

    } catch (error) {
      console.error("Failed to parse AI response:", error);
      alert("The AI returned a response in a format I couldn't understand. Please try again.");
    } finally {
      setIsLoading(false); // Set loading to false at the very end
    }
  };
  
  return (
    <div className="flex h-screen bg-black text-white">
      {/* Left Sidebar */}
      <div className="w-1/4 bg-gray-900 p-4 flex flex-col gap-y-4">
        <h2 className="text-xl font-bold text-white">World Index</h2>
        
        {/* --- UPDATED Button with loading state --- */}
        <button
          onClick={handleGenerateCharacter}
          className={`font-bold py-2 px-4 rounded ${isLoading ? 'bg-gray-500 cursor-not-allowed' : 'bg-blue-500 hover:bg-blue-600'}`}
          disabled={isLoading}
        >
          {isLoading ? 'Generating...' : 'Generate New Character'}
        </button>

        <div className="flex flex-col gap-y-2">
          <h3 className="text-lg font-semibold text-gray-300">Characters</h3>
          <ul className="pl-4 text-gray-400">
            {world.characters.map((char) => (
              <li
                key={char.name}
                className={`cursor-pointer hover:text-white ${selectedItem.name === char.name ? 'text-white font-bold' : ''}`}
                onClick={() => setSelectedItem(char)}
              >
                {char.name}
              </li>
            ))}
          </ul>
        </div>

        <div className="flex flex-col gap-y-2">
          <h3 className="text-lg font-semibold text-gray-300">Locations</h3>
          <ul className="pl-4 text-gray-400">
            {world.locations.map((loc) => (
              <li
                key={loc.name}
                className={`cursor-pointer hover:text-white ${selectedItem.name === loc.name ? 'text-white font-bold' : ''}`}
                onClick={() => setSelectedItem(loc)}
              >
                {loc.name}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Right Main Content */}
      <div className="w-3/4 p-8 overflow-y-auto">
        <div className="w-full h-64 bg-gray-800 rounded-lg flex items-center justify-center mb-6">
          <p className="text-gray-500">Character/Location Image</p>
        </div>

        <div>
          <h1 className="text-5xl font-bold text-white">{selectedItem.name}</h1>
          <p className="mt-4 text-lg text-gray-300">
            {selectedItem.description}
          </p>
          <p className="mt-2 text-md text-gray-400">
            {selectedItem.extra}
          </p>
        </div>
      </div>
    </div>
  );
}