"use client";
import { useState } from 'react';
import { generateText, generateImage } from '@/lib/ai';

// Add imageUrl to the type definition for our items
type WorldItem = {
  name: string;
  description: string;
  extra: string;
  imageUrl: string | null; // Can be a string or null
};

export default function Home() {
  const [world, setWorld] = useState({
    // --- UPDATED with imageUrl property ---
    characters: [
      { 
        name: 'Elara, the Sun-Priestess', 
        description: 'Elara is the high priestess of the Sun Temple...',
        extra: 'Her staff is said to contain a fragment of a fallen star.',
        imageUrl: null
      },
      { 
        name: 'Grak, the Stone-Hearted',
        description: 'Grak is a legendary warrior from the northern mountains...',
        extra: 'He carries a massive axe forged from the heart of a volcano.',
        imageUrl: null
      }
    ],
    locations: [
      { 
        name: 'The Sunken City of Aeridor',
        description: 'An ancient city lost to the depths of the ocean...',
        extra: 'Only accessible during a solar eclipse.',
        imageUrl: null
      },
    ]
  });

  // The selected item will now be of type WorldItem
  const [selectedItem, setSelectedItem] = useState<WorldItem>(world.characters[0]);
  const [isLoading, setIsLoading] = useState(false);

  // --- FULLY UPDATED handleGenerateCharacter function ---
  const handleGenerateCharacter = async () => {
    setIsLoading(true);
    console.log("Generating character...");
    const prompt = `Generate a new fantasy character for my world. 
    Provide a unique, cool-sounding name and a one-sentence description.
    Format the response as: "Name: [Character Name] | Description: [Character Description]"`;

    try {
      // Part 1: Generate Text
      const textResponse = await generateText(prompt);
      const name = textResponse.split('|')[0].replace('Name: ', '').trim();
      const description = textResponse.split('|')[1].replace('Description: ', '').trim();

      // Part 2: Generate Image
      console.log("Generating image for:", description);
      const imageUrl = await generateImage(description);
      console.log("Image URL:", imageUrl);

      // Part 3: Create new character object with all data
      const newCharacter: WorldItem = {
        name: name,
        description: description,
        extra: "This character was generated by AI.",
        imageUrl: imageUrl
      };

      setWorld(currentWorld => ({
        ...currentWorld,
        characters: [...currentWorld.characters, newCharacter]
      }));
      setSelectedItem(newCharacter);

    } catch (error) {
      console.error("Full generation process failed:", error);
      alert("There was an error in the generation process. Please check the console.");
    } finally {
      setIsLoading(false);
    }
  };
  
  return (
    <div className="flex h-screen bg-black text-white">
      {/* Left Sidebar */}
      <div className="w-1/ar bg-gray-900 p-4 flex flex-col gap-y-4 overflow-y-auto">
        <h2 className="text-xl font-bold text-white">World Index</h2>
        
        <button
          onClick={handleGenerateCharacter}
          className={`font-bold py-2 px-4 rounded ${isLoading ? 'bg-gray-500 cursor-not-allowed' : 'bg-blue-500 hover:bg-blue-600'}`}
          disabled={isLoading}
        >
          {isLoading ? 'Generating...' : 'Generate New Character'}
        </button>

        <div className="flex flex-col gap-y-2">
          <h3 className="text-lg font-semibold text-gray-300">Characters</h3>
          <ul className="pl-4 text-gray-400">
            {world.characters.map((char) => (
              <li
                key={char.name}
                className={`cursor-pointer hover:text-white ${selectedItem.name === char.name ? 'text-white font-bold' : ''}`}
                onClick={() => setSelectedItem(char)}
              >
                {char.name}
              </li>
            ))}
          </ul>
        </div>

        <div className="flex flex-col gap-y-2">
          <h3 className="text-lg font-semibold text-gray-300">Locations</h3>
          <ul className="pl-4 text-gray-400">
            {world.locations.map((loc) => (
              <li
                key={loc.name}
                className={`cursor-pointer hover:text-white ${selectedItem.name === loc.name ? 'text-white font-bold' : ''}`}
                onClick={() => setSelectedItem(loc)}
              >
                {loc.name}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Right Main Content */}
      <div className="w-3/4 p-8 overflow-y-auto">
        {/* --- UPDATED Image Display --- */}
        <div className="w-full h-80 bg-gray-800 rounded-lg flex items-center justify-center mb-6 overflow-hidden">
          {selectedItem.imageUrl ? (
            <img src={selectedItem.imageUrl} alt={selectedItem.name} className="w-full h-full object-cover" />
          ) : (
            <p className="text-gray-500">No Image Generated</p>
          )}
        </div>

        <div>
          <h1 className="text-5xl font-bold text-white">{selectedItem.name}</h1>
          <p className="mt-4 text-lg text-gray-300">
            {selectedItem.description}
          </p>
          <p className="mt-2 text-md text-gray-400">
            {selectedItem.extra}
          </p>
        </div>
      </div>
    </div>
  );
}